ClaimSize:
  # If true it will delete claim that have size bellow the specified size
  EnableClaimSize: true
  # Maximum size of a claim to define if it can be deleted
  MaxSizeClaim: 5000

# Config for clam removal affect by player inactivity
Inactivity:
  # If true it will delete claim that are older than a specific period
  EnableInactivty: true
  # Period in months to delete claims
  InactivityMonths: 12

# Config for claim removal affected by Bans
# Needed: LiteBans
Bans:
  # If true it will delete also claims of bannned players
  EnableBans: false