name: ClaimRemover
version: 0.0.1-SNAPSHOT
author: Freebuild
api-version: "1.13"
softdepend: [RedProtect, LiteBans]
description: Remover plugin for RedProtect Claim
main: fr.freebuild.claimremover.ClaimRemover
commands:
  claimremover:
    usage: /claimremover analyze|delete|export|import
    alias: [crm]
    permission: claimremover.commands
permissions:
  claimremover.*:
    description: Can use all feature of the plugin
    children:
     claimremover.commands.*: true
  claimremover.commands.*:
    description: Can use all commands
    children:
      claimremover.commands.analyze: true
      claimremover.commands.delete: true
      claimremover.commands.export: true
      claimremover.commands.import: true
  claimremover.commands.analyze:
    description: Can analyze all claims to delete
  claimremover.commands.delete:
    description: Can delete all claims analyzed
  claimremover.commands.export:
    description: Can export analyze to a csv file
  claimremover.commands.import:
    description: Can import analyze from a csv file
